export const recipes = [
  {
    name: "Palak Paneer",
    ingredients: [
      "spinach",
      "paneer",
      "garlic",
      "onion",
      "tomato",
      "ginger",
      "green chili",
      "turmeric",
      "garam masala",
    ],
    steps: [
      "Blanch spinach and blend to a puree.",
      "Sauté onions, garlic, and tomatoes.",
      "Add spices and spinach puree.",
      "Add paneer cubes and simmer.",
    ],
    image: "assets/images/palak-paneer-3.webp",
  },
  {
    name: "Chana Masala",
    ingredients: [
      "chickpeas",
      "onion",
      "tomato",
      "garlic",
      "ginger",
      "green chili",
      "garam masala",
      "cumin",
      "turmeric",
      "Mustard oil"
    ],
    steps: [
      "Cook soaked chickpeas.",
      "Sauté onion, garlic, and tomato.",
      "Add spices and cooked chickpeas.",
      "Simmer until thick.",
    ],
    image: "assets/images/chana_masala.jpg",
  },
  {
    name: "Masala Dosa",
    ingredients: [
      "rice",
      "urad dal",
      "potato",
      "mustard seeds",
      "curry leaves",
      "green chili",
      "turmeric",
      "onion",
    ],
    steps: [
      "Soak and ferment rice and dal batter.",
      "Prepare potato filling with spices.",
      "Spread batter on tawa and stuff with filling.",
      "Serve with chutney and sambar.",
    ],
    image: "assets/images/dosa.jpg",
  },
  {
    name: "Aloo Gobi",
    ingredients: [
      "potato",
      "cauliflower",
      "onion",
      "tomato",
      "garlic",
      "ginger",
      "turmeric",
      "cumin",
      "garam masala",
    ],
    steps: [
      "Sauté spices and aromatics.",
      "Add potato and cauliflower.",
      "Cook until tender and serve hot.",
    ],
    image: "assets/images/aloo_gobi.jpg",
  },
  {
    name: "Baingan Bharta",
    ingredients: [
      "eggplant",
      "onion",
      "tomato",
      "garlic",
      "ginger",
      "green chili",
      "coriander",
      "mustard oil",
    ],
    steps: [
      "Roast eggplant and mash it.",
      "Sauté onion, garlic, and tomato.",
      "Add mashed eggplant and cook.",
    ],
    image: "assets/images/baingan_bharta.jpg",
  },
  {
    name: "Rajma",
    ingredients: [
      "kidney beans",
      "onion",
      "tomato",
      "garlic",
      "ginger",
      "garam masala",
      "turmeric",
      "cumin",
    ],
    steps: [
      "Cook kidney beans.",
      "Prepare masala with onion, garlic, tomato.",
      "Add beans and simmer.",
    ],
    image: "assets/images/rajma.jpg",
  },
  {
    name: "Kadhi Pakora",
    ingredients: [
      "gram flour",
      "yogurt",
      "onion",
      "mustard seeds",
      "curry leaves",
      "ginger",
      "green chili",
      "turmeric",
    ],
    steps: [
      "Prepare yogurt and gram flour mixture.",
      "Make pakoras from gram flour and onion.",
      "Cook kadhi and add pakoras.",
    ],
    image: "assets/images/kadhi_pakora.jpg",
  },
  {
    name: "Bhindi Masala",
    ingredients: [
      "okra",
      "onion",
      "tomato",
      "garlic",
      "turmeric",
      "cumin",
      "amchur",
    ],
    steps: [
      "Sauté okra to reduce sliminess.",
      "Cook onion and tomato with spices.",
      "Add okra and simmer.",
    ],
    image: "assets/images/bhindi_masala.jpg",
  },
  {
    name: "Vegetable Biryani",
    ingredients: [
      "basmati rice",
      "carrot",
      "green beans",
      "peas",
      "potato",
      "onion",
      "tomato",
      "ginger",
      "garam masala",
      "mint",
      "coriander",
    ],
    steps: [
      "Cook vegetables with spices.",
      "Layer cooked rice and vegetables.",
      "Dum cook and serve with raita.",
    ],
    image: "assets/images/biryani.webp",
  },
  {
    name: "Paneer Butter Masala",
    ingredients: [
      "paneer",
      "butter",
      "cream",
      "onion",
      "tomato",
      "garam masala",
      "kasuri methi",
      "ginger garlic paste",
    ],
    steps: [
      "Sauté onion-tomato mixture with spices.",
      "Add cream and paneer cubes.",
      "Simmer and garnish with kasuri methi.",
    ],
    image: "assets/images/paneer butter masala.jpg",
  },
  {
    name: "Tawa Pulao",
    ingredients: [
      "rice",
      "bell peppers",
      "onion",
      "tomato",
      "peas",
      "pav bhaji masala",
      "garlic",
    ],
    steps: [
      "Sauté vegetables with masala.",
      "Mix with cooked rice.",
      "Stir fry and serve hot.",
    ],
    image: "assets/images/tawa.jpg",
  },
  {
    name: "Sambar",
    ingredients: [
      "yellow pigeon peas",
      "drumstick",
      "carrot",
      "eggplant",
      "tomato",
      "tamarind",
      "sambar powder",
      "mustard seeds",
      "curry leaves",
      "dried red chilies",
      "asafoetida",
      "coconut oil",
      "coriander",
    ],
    steps: [
      "Cook pigeon peas and mash.",
      "Extract tamarind pulp.",
      "Sauté mustard seeds, chilies, curry leaves, and asafoetida.",
      "Add vegetables, tamarind pulp, and sambar powder; boil.",
      "Mix in mashed dal and simmer.",
      "Garnish with coriander and serve.",
    ],
    image: "assets/images/sambar.jpg",
  },
  {
    name: "Gongura Pachadi",
    ingredients: [
      "gongura leaves",
      "dried red chilies",
      "cumin seeds",
      "coriander seeds",
      "garlic",
      "sesame oil",
    ],
    steps: [
      "Sauté gongura leaves until wilted.",
      "Dry roast cumin, coriander seeds, and chilies.",
      "Grind all with garlic into a paste.",
      "Cook paste in sesame oil and serve.",
    ],
    image: "assets/images/gongura_pachadi.jpg",
  },
  {
    name: "Sabudana Khichdi",
    ingredients: [
      "sago",
      "potato",
      "peanuts",
      "green chili",
      "cumin seeds",
      "rock salt",
      "ghee",
      "coriander",
      "lemon",
    ],
    steps: [
      "Soak sago and drain.",
      "Roast and grind peanuts.",
      "Sauté cumin seeds and green chili in ghee.",
      "Add boiled potato and sago, cook gently.",
      "Add rock salt, lemon juice, and coriander.",
    ],
    image: "assets/images/sabudana_khichdi.jpg",
  },
  {
    name: "Undhiyu",
    ingredients: [
      "raw banana",
      "potato",
      "eggplant",
      "green beans",
      "field beans",
      "coconut",
      "coriander",
      "green garlic",
      "sesame seeds",
      "coriander powder",
      "cumin powder",
      "turmeric",
      "red chili powder",
      "jaggery",
      "groundnut oil",
    ],
    steps: [
      "Mix coconut, coriander, garlic, sesame, and spices for stuffing.",
      "Stuff eggplants and mix with other vegetables.",
      "Cook with oil, jaggery, and water on low heat.",
      "Serve with puri.",
    ],
    image: "assets/images/undhiyu.jpg",
  },
  {
    name: "Bamboo Shoot Curry",
    ingredients: [
      "bamboo shoots",
      "potato",
      "onion",
      "ginger",
      "garlic",
      "dried red chilies",
      "cumin seeds",
      "turmeric",
      "mustard oil",
      "coriander",
    ],
    steps: [
      "Boil bamboo shoots and drain.",
      "Sauté cumin seeds and chilies in mustard oil.",
      "Add onion, ginger, and garlic.",
      "Cook with potatoes, bamboo shoots, and turmeric.",
      "Garnish with coriander and serve.",
    ],
    image: "assets/images/bamboo_shoot_curry.jpg",
  },
  {
    name: "Gulab Jamun",
    ingredients: [
      "khoya",
      "maida",
      "milk",
      "sugar",
      "cardamom",
      "saffron",
      "rose water",
      "ghee",
      "pistachios",
    ],
    steps: [
      "Make dough from khoya, maida, and milk; form balls.",
      "Deep-fry balls in ghee until golden.",
      "Prepare sugar syrup with cardamom and saffron.",
      "Soak balls in syrup and garnish with pistachios.",
    ],
    image: "assets/images/gulab_jamun.jpg",
  },
  {
    name: "Rava Kesari",
    ingredients: [
      "semolina",
      "sugar",
      "ghee",
      "saffron",
      "cardamom",
      "cashews",
      "raisins",
      "food coloring",
    ],
    steps: [
      "Fry cashews and raisins in ghee.",
      "Roast semolina until golden.",
      "Add boiling water and cook.",
      "Mix in sugar, saffron, cardamom, and coloring.",
      "Garnish with nuts and serve.",
    ],
    image: "assets/images/rava_kesari.jpg",
  },
  {
    name: "Dhokla",
    ingredients: [
      "gram flour",
      "semolina",
      "yogurt",
      "green chili",
      "ginger",
      "baking soda",
      "mustard seeds",
      "curry leaves",
      "coriander",
      "coconut",
      "vegetable oil",
      "sugar",
    ],
    steps: [
      "Mix gram flour, semolina, yogurt, and spices into batter.",
      "Add baking soda and steam batter.",
      "Sauté mustard seeds and curry leaves for tempering.",
      "Pour over dhokla, garnish with coconut and coriander.",
    ],
    image: "assets/images/dhokla.jpg",
  },
  {
    name: "Upma",
    ingredients: [
      "semolina",
      "onion",
      "green chili",
      "ginger",
      "mustard seeds",
      "urad dal",
      "curry leaves",
      "cashews",
      "ghee",
      "coriander",
      "lemon",
    ],
    steps: [
      "Roast semolina and set aside.",
      "Sauté mustard seeds, urad dal, cashews, and curry leaves in ghee.",
      "Add onion, green chili, and ginger; cook until soft.",
      "Add water, boil, and stir in semolina.",
      "Cook until thick, add lemon juice and coriander.",
    ],
    image: "assets/images/upma.jpg",
  },
  {
    name: "Idli",
    ingredients: [
      "idli rice",
      "urad dal",
      "fenugreek seeds",
      "salt",
      "fresh coconut",
      "chutney powder",
      "coconut oil",
    ],
    steps: [
      "Soak idli rice, urad dal, and fenugreek seeds; grind into batter.",
      "Ferment batter overnight.",
      "Pour batter into idli molds and steam for 10-12 minutes.",
      "Serve with coconut chutney and chutney powder.",
    ],
    image: "assets/images/idli.jpg",
  },
  {
    name: "Khaman Dhokla",
    ingredients: [
      "gram flour",
      "yogurt",
      "eno fruit salt",
      "green chili",
      "ginger",
      "mustard seeds",
      "curry leaves",
      "coriander",
      "fresh coconut",
      "sesame seeds",
      "vegetable oil",
      "sugar",
    ],
    steps: [
      "Mix gram flour, yogurt, green chili, and ginger into batter.",
      "Add eno fruit salt and steam batter for 15 minutes.",
      "Sauté mustard seeds, curry leaves, and sesame seeds in oil.",
      "Pour tempering over dhokla, garnish with coconut and coriander.",
    ],
    image: "assets/images/khaman_dhokla.jpg",
  },
  {
    name: "Aloo Paratha",
    ingredients: [
      "wheat flour",
      "potato",
      "green chili",
      "coriander",
      "cumin powder",
      "red chili powder",
      "amchur",
      "ghee",
      "salt",
    ],
    steps: [
      "Boil and mash potatoes, mix with spices and coriander.",
      "Knead wheat flour into dough and roll into circles.",
      "Stuff with potato mixture, roll flat, and cook on tawa with ghee.",
      "Serve with yogurt or pickle.",
    ],
    image: "assets/images/pp.webp",
  },
  {
    name: "Poha",
    ingredients: [
      "poha",
      "onion",
      "green chili",
      "mustard seeds",
      "curry leaves",
      "turmeric",
      "peanuts",
      "coriander",
      "lemon",
      "vegetable oil",
    ],
    steps: [
      "Rinse poha and drain.",
      "Sauté mustard seeds, peanuts, and curry leaves in oil.",
      "Add onion, green chili, and turmeric; cook until soft.",
      "Add poha, mix gently, and cook for 5 minutes.",
      "Add lemon juice and coriander, serve hot.",
    ],
    image: "assets/images/gujarati-batata-poha-recipe.jpg",
  },
  {
    name: "Oats Upma",
    ingredients: [
      "oats",
      "onion",
      "carrot",
      "peas",
      "green chili",
      "mustard seeds",
      "urad dal",
      "curry leaves",
      "vegetable oil",
      "coriander",
    ],
    steps: [
      "Roast oats and set aside.",
      "Sauté mustard seeds, urad dal, and curry leaves in oil.",
      "Add onion, green chili, carrot, and peas; cook until soft.",
      "Add water, boil, and stir in oats.",
      "Cook until thick, garnish with coriander.",
    ],
    image: "assets/images/oats_upma.jpg",
  },
  {
    name: "Bread Upma",
    ingredients: [
      "bread",
      "onion",
      "tomato",
      "green chili",
      "mustard seeds",
      "curry leaves",
      "turmeric",
      "vegetable oil",
      "coriander",
    ],
    steps: [
      "Cut bread into cubes.",
      "Sauté mustard seeds and curry leaves in oil.",
      "Add onion, green chili, and tomato; cook until soft.",
      "Add turmeric and bread cubes, stir-fry until crisp.",
      "Garnish with coriander and serve.",
    ],
    image: "assets/images/bread_upma.jpg",
  },
  {
    name: "Vermicelli Upma",
    ingredients: [
      "vermicelli",
      "onion",
      "green chili",
      "carrot",
      "peas",
      "mustard seeds",
      "urad dal",
      "curry leaves",
      "vegetable oil",
      "coriander",
    ],
    steps: [
      "Roast vermicelli and set aside.",
      "Sauté mustard seeds, urad dal, and curry leaves in oil.",
      "Add onion, green chili, carrot, and peas; cook until soft.",
      "Add water, boil, and stir in vermicelli.",
      "Cook until water is absorbed, garnish with coriander.",
    ],
    image: "assets/images/vermicelli_upma.jpg",
  },
  {
    name: "Rava Idli",
    ingredients: [
      "semolina",
      "yogurt",
      "eno fruit salt",
      "green chili",
      "ginger",
      "cashews",
      "mustard seeds",
      "curry leaves",
      "vegetable oil",
      "coriander",
    ],
    steps: [
      "Roast semolina and mix with yogurt, green chili, and ginger.",
      "Add eno fruit salt and pour into idli molds.",
      "Steam for 10-12 minutes.",
      "Sauté mustard seeds, cashews, and curry leaves; pour over idlis.",
      "Garnish with coriander and serve.",
    ],
    image: "assets/images/rava_idli.jpg",
  },
  {
    name: "Thepla",
    ingredients: [
      "wheat flour",
      "fenugreek leaves",
      "green chili",
      "ginger",
      "turmeric",
      "red chili powder",
      "coriander powder",
      "yogurt",
      "vegetable oil",
    ],
    steps: [
      "Mix wheat flour, fenugreek leaves, spices, and yogurt into dough.",
      "Roll into thin circles.",
      "Cook on tawa with oil until golden on both sides.",
      "Serve with yogurt or pickle.",
    ],
    image: "assets/images/tepla.webp",
  },
];
